import type { Metadata } from "next";
import { Inter,Bebas_Neue,Padauk,Montserrat} from "next/font/google";


import "./globals.css";
import "./styles.css";

const inter_init = Inter({ subsets: ["latin"] });

const bebas_init = Bebas_Neue({ 
  subsets: ["latin"],
  weight:['400'],
  variable:'--font-bebas'
});

const paduk = Padauk({
  subsets: ["latin"],
  weight:['400'],
  variable:'--font-padauk'
});

const mont = Montserrat({
  subsets: ["latin"],
  weight:['400'],
  variable:'--font-montserrat'
});




export const metadata: Metadata = {
  title: "PeakyBlinders_Fanpage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={('')}>
      <body className={bebas_init.className}>{children}</body>
    </html>
  );
}
